; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino

; 设置串口监视器波特率
monitor_speed = 115200

; 自动下载所需的第三方库
lib_deps = 
	bblanchon/ArduinoJson @ ^6.21.3
	arduino-libraries/NTPClient @ ^3.2.1
    https://github.com/jeason-j/ESP8266-Seniverse.git
